[package]
name = "lore-parser"
version = "0.1.0"
authors = ["Leandro Ostera <leandro@abstractmachines.dev>"]
edition = "2018"

[dependencies]
logos = "0.12"
thiserror = "1.0"
lore-ast = { path = "../lore-ast" }

[dev-dependencies]
pretty_assertions = "0.7"
insta = "1.8"
